name: "prepare action"
description: "Prepare the environment for the action"
inputs:
  version:
    description: "Node.js version to use"
    required: true
    default: '24'

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.version }}
  