name: Build and Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: '24'

  test:
    uses: ./.github/workflows/test.yaml
    needs: build
    with:
      version: '24'
  
  codeScan:
    uses: ./.github/workflows/sonar.yaml
    
  
  # fileSacn:
  #   # Trivy FS

  # DockerBuild:
  #   #
  
  # DcokerScan:
  #   # Trivy Docker
