name: Trivy Docker Image Scan

on: workflow_call

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: kyawthethtun/crud-app:${{ github.sha }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'