name: Trivy FS Scan

on: workflow_call

jobs:
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          exit-code: 1
          severity: "CRITICAL"